### ISSUE TITLE
Remove Files

### ISSUE THREAD

**Issue by thematthewchen** [SOCR/BlueML-Issues#101]
When a user uploads one file and then removes it, the table entry disappears when there should still be one table line instead of zero. The only way to get the line back is to click the "Add Another File" (which is in a very awkward location on the page and needs to be relocated along with the "Upload ECG File" button).

Also, the name of the first uploaded file is still in the table column name when it should not be since the file was removed.

**Comment by justinpan0** [comment]
This issue looks similar to Ticket #90, which has been moved to review already.
